# EQUA Beacon Chain Configuration
# Based on minimal preset for fast testing

CONFIG_NAME: 'equa'

# Preset
PRESET_BASE: 'minimal'

# Genesis
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 1
MIN_GENESIS_TIME: 0
GENESIS_FORK_VERSION: 0x00003782
GENESIS_DELAY: 10

# Time parameters (minimal for fast testing)
SECONDS_PER_SLOT: 6
SLOTS_PER_EPOCH: 8
EPOCHS_PER_ETH1_VOTING_PERIOD: 4

# Validator cycle
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 256
SHARD_COMMITTEE_PERIOD: 64

# Validator
ETH1_FOLLOW_DISTANCE: 16
TARGET_AGGREGATORS_PER_COMMITTEE: 2
RANDOM_SUBNETS_PER_VALIDATOR: 1
EPOCHS_PER_RANDOM_SUBNET_SUBSCRIPTION: 4

# Deposit contract
DEPOSIT_CHAIN_ID: 3782
DEPOSIT_NETWORK_ID: 3782
DEPOSIT_CONTRACT_ADDRESS: 0x0000000000000000000000000000000000000000

# Networking
ATTESTATION_SUBNET_COUNT: 2

# Altair
ALTAIR_FORK_VERSION: 0x01003782
ALTAIR_FORK_EPOCH: 0

# Bellatrix (Merge)
BELLATRIX_FORK_VERSION: 0x02003782
BELLATRIX_FORK_EPOCH: 0
TERMINAL_TOTAL_DIFFICULTY: 999999999999999999
TERMINAL_BLOCK_HASH: 0x0000000000000000000000000000000000000000000000000000000000000000
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 0

# Capella (Shanghai)
CAPELLA_FORK_VERSION: 0x03003782
CAPELLA_FORK_EPOCH: 0

# Deneb (Cancun)
DENEB_FORK_VERSION: 0x04003782
DENEB_FORK_EPOCH: 0

# Electra
ELECTRA_FORK_VERSION: 0x05003782
ELECTRA_FORK_EPOCH: 18446744073709551615

# Fulu (Future fork - disabled)
FULU_FORK_VERSION: 0x06003782
FULU_FORK_EPOCH: 18446744073709551615
